In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import math as mt
import random as rng

from sklearn import preprocessing

In [2]:
data = np.load("dataFormatted/Train.npy", allow_pickle=True)
target = np.load("dataFormatted/TrainTarget.npy", allow_pickle=True)
totalSims = 100

newData = []
newTarget = []

#for dataLine, targetLine in zip(data, target):
#    if targetLine <= 120:
#        newData.append(dataLine)
#        newTarget.append(targetLine)
        
#data = np.array(newData)
#target = np.array(newTarget)

In [3]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
df = pd.DataFrame(data)
df = df.drop([0, 9, 17, 18], axis=1)

normTrain = scaler.fit_transform(df.to_numpy())

In [4]:
scaler = preprocessing.StandardScaler()

scaledTrain = scaler.fit_transform(data)

from sklearn.decomposition import PCA
pca = PCA(.96)
pcaTrain = pca.fit_transform(scaledTrain)


In [5]:
from sklearn.svm import SVR
from sklearn import ensemble
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import RadiusNeighborsRegressor

In [6]:
sgd = linear_model.SGDRegressor(loss='squared_loss')


forest = ensemble.RandomForestRegressor(max_depth=20, n_estimators=100)
extraForest = ensemble.ExtraTreesRegressor(n_estimators=20, max_depth=100)

svr = SVR(kernel='poly', coef0=4)

linearRgr = LinearRegression()
knn = KNeighborsRegressor(75, weights='distance')


In [7]:
from sklearn.utils import shuffle

normTrain, target = shuffle(normTrain, target)


In [8]:
#forest.fit(X_train, y_train)
#results = forest.predict(X_test)
#print(mean_squared_error(results, y_test))
#print(mean_absolute_error(results, y_test))
cross_val_score(forest, normTrain, target, scoring="neg_mean_absolute_error")

array([-29.87331813, -29.45880513, -30.01910315, -28.94931536,
       -29.44213913])

In [9]:
cross_val_score(extraForest, normTrain, target, scoring="neg_mean_absolute_error")

array([-30.31894839, -30.26914687, -30.34934561, -29.45295686,
       -30.12487882])

In [10]:
cross_val_score(svr, normTrain, target, scoring="neg_mean_absolute_error")

array([-30.21841903, -29.93039479, -30.04031362, -29.41863045,
       -30.0173639 ])

In [11]:
cross_val_score(linearRgr, normTrain, target, scoring="neg_mean_absolute_error")

array([-34.36145803, -34.04615731, -34.69486665, -33.45178829,
       -34.12513451])

In [12]:
cross_val_score(knn, normTrain, target, scoring="neg_mean_absolute_error")

array([-31.14786217, -30.58015448, -30.8201173 , -29.82118645,
       -30.27403101])

In [13]:
cross_val_score(sgd, normTrain, target, scoring="neg_mean_absolute_error")

array([-34.44433351, -34.08064934, -34.63522001, -33.56490611,
       -34.0206986 ])